name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: docker-compose up -d 
    - name: Export env variable
      run : bash export_env.sh
    - name: Test  
      run: docker-compose run -e DB_NAME=hs -e DB_TEST_NAME=hs_test -e DB_USER=hs -e DB_PASSWORD=elfenlied1, patientsapp lein test 
